# This file generated by Quarto; do not edit by hand.

from __future__ import annotations

from pathlib import Path
from shiny import App, Inputs, Outputs, Session, ui




def server(input: Inputs, output: Outputs, session: Session) -> None:
    from shiny import render, reactive
    from shiny.express import input, ui

    # ========================================================================

    ui.input_radio_buttons(  
            "radio_1",  
            "Radio buttons",  
            {"1": "Option 1", "2": "Option 2", "3": "Option 3"},  
    ) 

    ui.input_radio_buttons(  
            "radio_2",  
            "Radio buttons",  
            {"1": "Option 1", "2": "Option 2", "3": "Option 3"},  
    ) 

    # ========================================================================

    ui.input_checkbox_group(  
        "checkbox_group",  
        "Checkbox group",  
        {  
            "a": "A",  
            "b": "B",  
            "c": "C",  
        },  
    )  

    # ========================================================================

    @reactive.calc
    def add_checkboxes():
        return int(input.radio_1()) + int(input.radio_2())

    # ========================================================================

    @render.ui
    def radio_value():
        return add_checkboxes()

    # ========================================================================

    @render.text
    def checkbox_group_value():
        return ", ".join(input.checkbox_group())

    # ========================================================================



    return None


_static_assets = ["q-shiny-1_files"]
_static_assets = {"/" + sa: Path(__file__).parent / sa for sa in _static_assets}

app = App(
    Path(__file__).parent / "q-shiny-1.html",
    server,
    static_assets=_static_assets,
)
