# This file generated by Quarto; do not edit by hand.

from __future__ import annotations

from pathlib import Path
from shiny import App, Inputs, Outputs, Session, ui




def server(input: Inputs, output: Outputs, session: Session) -> None:
    from shiny import App, render
    from shiny.express import input, ui

    ui.input_checkbox("checkbox", "Checkbox", False)

    # ========================================================================

    @render.ui
    def value():
        return input.checkbox()

    # ========================================================================



    return None


_static_assets = ["q-shiny-core_files"]
_static_assets = {"/" + sa: Path(__file__).parent / sa for sa in _static_assets}

app = App(
    Path(__file__).parent / "q-shiny-core.html",
    server,
    static_assets=_static_assets,
)
